; kantian.metta - Western Deontological Ethics

(applies-to rule action)
(property rule universal)
(= (not-universalizable $rule) (wrong $rule))

; Individuals are ends, not means
(not-property individual fungible)
(cannot-weigh suffering benefit)
(inherent dignity being)
(not-property dignity calculable)
(undermines weighing dignity)

; Duty and obligation
(not-contingent duty inclination)
(independent obligation desire)
(= (exists duty) (regardless-of (desire agent)))
