; ubuntu.metta - Ubuntu Relational Ethics

(because i-am we-are)
(exists-through person community)
(exists-through community person)
(not-prior person community)
(not-prior community person)

; This is a re-entry. Neither comes first.
(certainty (priority person community) Imaginary)
(certainty (priority community person) Imaginary)

; Mutual flourishing
(= (flourishing self) (requires (flourishing other)))
(= (flourishing other) (requires (flourishing self)))
(= (harm community) (harm self))
(= (harm self) (harm community))
(not-separable individual community)
