// <copyright file="ModelTypeTests.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using Ouroboros.Abstractions.Monads;
using Ouroboros.Core.LawsOfForm;

namespace Ouroboros.Core.Tests.LawsOfForm;

/// <summary>
/// Tests for the <see cref="ToolCall"/> record.
/// </summary>
[Trait("Category", "Unit")]
public class ToolCallTests
{
    [Fact]
    public void Constructor_SetsAllProperties()
    {
        var metadata = new Dictionary<string, string> { ["source"] = "llm" };
        var timestamp = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        var call = new ToolCall("search", "{\"q\":\"test\"}", 0.95, metadata, "call-1", timestamp);

        call.ToolName.Should().Be("search");
        call.Arguments.Should().Be("{\"q\":\"test\"}");
        call.Confidence.Should().Be(0.95);
        call.Metadata.Should().ContainKey("source");
        call.CallId.Should().Be("call-1");
        call.RequestedAt.Should().Be(timestamp);
    }

    [Fact]
    public void Constructor_DefaultConfidence_Is1()
    {
        var call = new ToolCall("tool", "args");

        call.Confidence.Should().Be(1.0);
    }

    [Fact]
    public void Constructor_DefaultMetadata_IsEmpty()
    {
        var call = new ToolCall("tool", "args");

        call.Metadata.Should().BeEmpty();
    }

    [Fact]
    public void Constructor_DefaultCallId_IsAutoGenerated()
    {
        var call = new ToolCall("tool", "args");

        call.CallId.Should().NotBeNullOrWhiteSpace();
        Guid.TryParse(call.CallId, out _).Should().BeTrue();
    }

    [Fact]
    public void Constructor_DefaultRequestedAt_UsesUtcNow()
    {
        var before = DateTime.UtcNow;
        var call = new ToolCall("tool", "args");
        var after = DateTime.UtcNow;

        call.RequestedAt.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }

    [Fact]
    public void RecordEquality_SameValues_AreEqual()
    {
        var ts = DateTime.UtcNow;
        var c1 = new ToolCall("tool", "args", 1.0, callId: "id", requestedAt: ts);
        var c2 = new ToolCall("tool", "args", 1.0, callId: "id", requestedAt: ts);

        c1.Should().Be(c2);
    }
}

/// <summary>
/// Tests for the <see cref="ToolResult"/> record.
/// </summary>
[Trait("Category", "Unit")]
public class ToolResultTests
{
    private static ToolCall CreateToolCall() => new("tool", "args");

    [Fact]
    public void Constructor_SetsAllProperties()
    {
        var call = CreateToolCall();
        var timestamp = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var duration = TimeSpan.FromMilliseconds(150);

        var result = new ToolResult("output", call, ExecutionStatus.Success, duration, "err", timestamp);

        result.Output.Should().Be("output");
        result.ToolCall.Should().Be(call);
        result.Status.Should().Be(ExecutionStatus.Success);
        result.Duration.Should().Be(duration);
        result.ErrorMessage.Should().Be("err");
        result.CompletedAt.Should().Be(timestamp);
    }

    [Fact]
    public void Constructor_DefaultErrorMessage_IsNull()
    {
        var result = new ToolResult("output", CreateToolCall(), ExecutionStatus.Success, TimeSpan.Zero);

        result.ErrorMessage.Should().BeNull();
    }

    [Fact]
    public void Constructor_DefaultCompletedAt_UsesUtcNow()
    {
        var before = DateTime.UtcNow;
        var result = new ToolResult("output", CreateToolCall(), ExecutionStatus.Success, TimeSpan.Zero);
        var after = DateTime.UtcNow;

        result.CompletedAt.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }

    [Fact]
    public void Success_CreatesSuccessResult()
    {
        var call = CreateToolCall();
        var duration = TimeSpan.FromSeconds(1);

        var result = ToolResult.Success("done", call, duration);

        result.Output.Should().Be("done");
        result.ToolCall.Should().Be(call);
        result.Status.Should().Be(ExecutionStatus.Success);
        result.Duration.Should().Be(duration);
        result.ErrorMessage.Should().BeNull();
    }

    [Fact]
    public void Failure_CreatesFailedResult()
    {
        var call = CreateToolCall();
        var duration = TimeSpan.FromSeconds(2);

        var result = ToolResult.Failure("something broke", call, duration);

        result.Output.Should().BeEmpty();
        result.ToolCall.Should().Be(call);
        result.Status.Should().Be(ExecutionStatus.Failed);
        result.Duration.Should().Be(duration);
        result.ErrorMessage.Should().Be("something broke");
    }
}

/// <summary>
/// Tests for the <see cref="UserInfo"/> record.
/// </summary>
[Trait("Category", "Unit")]
public class UserInfoTests
{
    [Fact]
    public void Constructor_SetsProperties()
    {
        var permissions = new HashSet<string> { "read", "write" };
        var user = new UserInfo("user-123", permissions);

        user.UserId.Should().Be("user-123");
        user.Permissions.Should().HaveCount(2);
    }

    [Fact]
    public void HasPermission_ExistingPermission_ReturnsTrue()
    {
        var user = new UserInfo("u1", new HashSet<string> { "admin", "read" });

        user.HasPermission("admin").Should().BeTrue();
    }

    [Fact]
    public void HasPermission_MissingPermission_ReturnsFalse()
    {
        var user = new UserInfo("u1", new HashSet<string> { "read" });

        user.HasPermission("admin").Should().BeFalse();
    }

    [Fact]
    public void HasPermission_EmptyPermissions_ReturnsFalse()
    {
        var user = new UserInfo("u1", new HashSet<string>());

        user.HasPermission("anything").Should().BeFalse();
    }

    [Fact]
    public void RecordEquality_SameValues_AreEqual()
    {
        var perms = new HashSet<string> { "read" };
        var u1 = new UserInfo("u1", perms);
        var u2 = new UserInfo("u1", perms);

        u1.Should().Be(u2);
    }
}

/// <summary>
/// Tests for the <see cref="PendingApproval"/> record.
/// </summary>
[Trait("Category", "Unit")]
public class PendingApprovalTests
{
    [Fact]
    public void Constructor_SetsAllProperties()
    {
        var call = new ToolCall("tool", "args");
        var decision = AuditableDecision<ToolResult>.Uncertain("err", "reason");
        var queuedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        var pending = new PendingApproval("q-1", call, decision, queuedAt);

        pending.QueueId.Should().Be("q-1");
        pending.Call.Should().Be(call);
        pending.OriginalDecision.Should().Be(decision);
        pending.QueuedAt.Should().Be(queuedAt);
    }

    [Fact]
    public void RecordEquality_SameValues_AreEqual()
    {
        var call = new ToolCall("tool", "args", callId: "c1", requestedAt: DateTime.MinValue);
        var decision = AuditableDecision<ToolResult>.Uncertain("err", "reason");
        var ts = DateTime.UtcNow;

        var p1 = new PendingApproval("q-1", call, decision, ts);
        var p2 = new PendingApproval("q-1", call, decision, ts);

        p1.Should().Be(p2);
    }
}

/// <summary>
/// Tests for the <see cref="StateTransition{TState}"/> record.
/// </summary>
[Trait("Category", "Unit")]
public class StateTransitionTests
{
    [Fact]
    public void Constructor_SetsAllProperties()
    {
        var timestamp = DateTimeOffset.UtcNow;
        var form = Form.Mark;
        var state = Option<string>.Some("active");
        var reason = "activation triggered";

        var transition = new StateTransition<string>(timestamp, form, state, reason);

        transition.Timestamp.Should().Be(timestamp);
        transition.Form.Should().Be(form);
        transition.State.Should().Be(state);
        transition.Reason.Should().Be(reason);
    }

    [Fact]
    public void Constructor_WithNoneState_SetsCorrectly()
    {
        var transition = new StateTransition<int>(
            DateTimeOffset.UtcNow, Form.Void, Option<int>.None(), "deactivated");

        transition.State.HasValue.Should().BeFalse();
    }

    [Fact]
    public void RecordEquality_SameValues_AreEqual()
    {
        var ts = DateTimeOffset.UtcNow;
        var t1 = new StateTransition<string>(ts, Form.Mark, Option<string>.Some("a"), "r");
        var t2 = new StateTransition<string>(ts, Form.Mark, Option<string>.Some("a"), "r");

        t1.Should().Be(t2);
    }

    [Fact]
    public void RecordEquality_DifferentReason_AreNotEqual()
    {
        var ts = DateTimeOffset.UtcNow;
        var t1 = new StateTransition<string>(ts, Form.Mark, Option<string>.Some("a"), "reason1");
        var t2 = new StateTransition<string>(ts, Form.Mark, Option<string>.Some("a"), "reason2");

        t1.Should().NotBe(t2);
    }
}
