#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// System imports
global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
// Foundation layer
global using Ouroboros.Core.Monads;
global using Ouroboros.Domain;
global using Ouroboros.Domain.Autonomous;
global using Ouroboros.Domain.Embodied;
global using Ouroboros.Domain.Events;
global using Ouroboros.Domain.States;
global using Ouroboros.Domain.Vectors;
global using Ouroboros.Tools;
